server:
  port: 8531
redis:
  port: 6379
  host: 127.0.0.1
  password:
  topicName: panda-ws
logging:
  file: /comicpanda/logs/app/ws/application.log
---

spring:
  profiles: production
redis:
  topicName: panda-ws
  port: 6379
  host: redissv
  password: